# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - amovergan/*
  - master

pr: none

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(tag)

          - task: Docker@2
            inputs:
              containerRegistry: 'gcr.altenar-dev-ppenvs'
              command: 'login'
              addPipelineData: false
              addBaseImageData: false

          - task: Docker@2
            inputs:
              containerRegistry: 'gcr.altenar-dev-ppenvs'
              repository: 'altenar-dev-ppenvs/amovergan-todo'
              command: 'push'


  