apiVersion: apps/v1
kind: Deployment
metadata:
  name: amovergan-todo-list
  labels:
    app: amovergan-todo-list
spec:
  selector:
    matchLabels:
      app: amovergan-todo-list
  template:
    metadata:
      name: amovergan-todo-list
      labels:
        app: amovergan-todo-list
    spec:
      containers:
        - name: amovergan-todo-list-nginx
          image: bitnami/nginx:latest
          volumeMounts:
            - name: config-volume
              mountPath: /opt/bitnami/nginx/conf/server_blocks/
          ports:
            - containerPort: 8080
        - name: amovergan-todo-list-php-fpm
          image: gcr.io/altenar-dev-ppenvs/amovergan-todo
      volumes:
        - name: config-volume
          configMap:
            name: nginx-conf
