apiVersion: v1
kind: Service
metadata:
  name: amovergan-todo-list
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: amovergan-todo-list
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: amovergan-todo-list